season: 2024
s3_geo_data_key: "geo_data/circuits"
s3_model_key : "model"

gp_circuits:
  "Bahrain": "bh-2002.geojson"
  "Saudi Arabia": "sa-2021.geojson"
  "Australia": "au-1953.geojson"
  "Japan": "jp-1962.geojson"
  "China": "cn-2004.geojson"
  "Miami": "us-2022.geojson"
  "Emilia Romagna": "it-1953.geojson"
  "Monaco": "mc-1929.geojson"
  "Canada": "ca-1978.geojson"
  "Spain": "es-1991.geojson"
  "Austria": "at-1969.geojson"
  "Great Britain": "gb-1948.geojson"
  "Hungary": "hu-1986.geojson"
  "Belgium": "be-1925.geojson"
  "Netherlands": "nl-1948.geojson"
  "Italy": "it-1922.geojson"
  "Azerbaijan": "az-2016.geojson"
  "Singapore": "sg-2008.geojson"
  "United States": "us-2012.geojson"
  "Mexico": "mx-1962.geojson"
  "Brazil": "br-1940.geojson"
  "Las Vegas": "us-2023.geojson"
  "Qatar": "qa-2004.geojson"
  "Abu Dhabi": "ae-2009.geojson"