geo_data_dir: "data/f1-circuits-master/circuits"
gp_circuits:
  "Bahrain Grand Prix": "bh-2002.geojson"
  "Saudi Arabian Grand Prix": "sa-2021.geojson"
  "Australian Grand Prix": "au-1953.geojson"
  "Japanese Grand Prix": "jp-1962.geojson"
  "Chinese Grand Prix": "cn-2004.geojson"
  "Miami Grand Prix": "us-2022.geojson"
  "Emilia Romagna Grand Prix": "it-1953.geojson"
  "Monaco Grand Prix": "mc-1929.geojson"
  "Canadian Grand Prix": "ca-1978.geojson"
  "Spanish Grand Prix": "es-1991.geojson"
  "Austrian Grand Prix": "at-1969.geojson"
  "British Grand Prix": "gb-1948.geojson"
  "Hungarian Grand Prix": "hu-1986.geojson"
  "Belgian Grand Prix": "be-1925.geojson"
  "Dutch Grand Prix": "nl-1948.geojson"
  "Italian Grand Prix": "it-1922.geojson"
  "Azerbaijan Grand Prix": "az-2016.geojson"
  "Singapore Grand Prix": "sg-2008.geojson"
  "United States Grand Prix": "us-2012.geojson"
  "Mexico City Grand Prix": "mx-1962.geojson"
  "São Paulo Grand Prix": "br-1940.geojson"
  "Las Vegas Grand Prix": "us-2023.geojson"
  "Qatar Grand Prix": "qa-2004.geojson"
  "Abu Dhabi Grand Prix": "ae-2009.geojson"